version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    open-pull-requests-limit: 10
    reviewers:
      - beverts312
    assignees:
      - beverts312
    labels:
      - dependencies
